version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    restart: unless-stopped

  chroma_db:
    image: chromadb/chroma
    container_name: chroma_db
    ports:
      - "8000:8000"
    volumes:
      - ./chromadb:/chroma/chroma
    restart: unless-stopped

volumes:
  chromadb:
